### ISSUE TITLE
RStudioConsoleRender always opens in browser

### ISSUE THREAD

**Issue by torfason** [jeffjjohnston/RStudioConsoleRender#1]
This may well be ignorance rather than issue but I have not been able to get RStudioConsoleRender in the viewer pane. It always seems to want to open the output in a browser, and the regular config settings for RStudio don't seem to do anything.

This is on a mac.

I'm loving the RStudioConsoleRender, this is the only issue that is a bit of a downer. I regularly have RMarkdown files with packages that take a few seconds to load, and with drake to cut the rest of the run-time down to essentially zero for most compiles, the libraries become the main drag for doing quick compiles.

**Comment by jeffjjohnston** [comment]
Hi @torfason,

You are correct that the addin always opens the rendered document in the browser. This is because RStudio is very picky about which files it will open in the viewer pane. Your suggestion prompted me to investigate how to get the rendered document into the viewer pane and I believe I found a solution. If you reinstall the latest version of the addin, you can set an option to use the viewer pane:

```r
options("RStudioConsoleRender.viewer_mode"="viewer_pane")
```

This option will copy the rendered document into the RStudio session temporary directory before opening it, which will trigger RStudio to use the viewer pane. The other possible values are `browser` and `none`. Give it a try and let me know if you have any issues!

**Comment by torfason** [comment]
I can confirm that this works like a charm :-)

Thank you, RstudioConsoleRender will probably become my main way of rendering markdown from now on.
